QUESTION_BANK = {
    "Software Engineer": [
        {"q": "Which data structure is best for implementing a priority queue?", "options": ["Stack", "Linked List", "Heap", "Array"], "answer": "Heap"},
        {"q": "What is the worst-case time complexity of QuickSort?", "options": ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], "answer": "O(n^2)"},
        {"q": "Which OOP concept allows a class to have multiple methods with the same name but different parameters?", "options": ["Overriding", "Encapsulation", "Polymorphism", "Overloading"], "answer": "Overloading"},
        {"q": "Which data structure operates on a Last In, First Out (LIFO) principle?", "options": ["Queue", "Tree", "Stack", "Graph"], "answer": "Stack"},
        {"q": "What is the time complexity of binary search on a sorted array?", "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"], "answer": "O(log n)"},
        {"q": "Which of the following is NOT a property of an ACID transaction?", "options": ["Atomicity", "Consistency", "Isolation", "Redundancy"], "answer": "Redundancy"},
        {"q": "What is the main purpose of an Operating System?", "options": ["Compile code", "Manage hardware and software resources", "Edit text", "Browse the internet"], "answer": "Manage hardware and software resources"},
        {"q": "In OOP, what does encapsulation refer to?", "options": ["Inheriting from multiple classes", "Bundling data and methods that work on that data", "Overriding methods", "Executing multiple threads"], "answer": "Bundling data and methods that work on that data"},
        {"q": "Which graph traversal algorithm uses a queue?", "options": ["Depth-First Search (DFS)", "Breadth-First Search (BFS)", "Dijkstra's Algorithm", "A* search"], "answer": "Breadth-First Search (BFS)"},
        {"q": "What commonly causes a memory leak?", "options": ["Using too many pointers", "Failing to release memory that is no longer needed", "Compiling code without optimization", "Running infinite loops"], "answer": "Failing to release memory that is no longer needed"},
        {"q": "Which data structure is naturally suited for Depth-First Search (DFS)?", "options": ["Queue", "Heap", "Stack", "Array"], "answer": "Stack"},
        {"q": "What is polymorphism?", "options": ["Writing to multiple files", "The ability of different objects to respond to the same method call", "Hiding internal states", "Inheriting attributes"], "answer": "The ability of different objects to respond to the same method call"},
        {"q": "In relational databases, what does SQL stand for?", "options": ["Structured Question Language", "System Query Language", "Structured Query Language", "Standard Query Logic"], "answer": "Structured Query Language"},
        {"q": "What is a race condition in an OS?", "options": ["A CPU optimization technique", "When multiple threads access shared data concurrently and outcome depends on execution order", "A fast boot sequence", "A compilation error"], "answer": "When multiple threads access shared data concurrently and outcome depends on execution order"},
        {"q": "What is the average time complexity of inserting into a hash table?", "options": ["O(1)", "O(log n)", "O(n)", "O(n^2)"], "answer": "O(1)"},
        {"q": "What does a foreign key do in a database?", "options": ["Encrypts the table", "Links two tables together", "Automatically increments", "Stores binary large objects"], "answer": "Links two tables together"},
        {"q": "Which sorting algorithm is stable by default?", "options": ["Quick Sort", "Heap Sort", "Merge Sort", "Selection Sort"], "answer": "Merge Sort"},
        {"q": "What describes a deadlock state?", "options": ["CPU usage is at 100%", "Each process is waiting for a resource held by another", "A process has completely finished", "Memory is fully allocated"], "answer": "Each process is waiting for a resource held by another"},
        {"q": "Which tree ensures the left child is smaller and the right child is larger?", "options": ["B-Tree", "Binary Search Tree", "AVL Tree", "Trie"], "answer": "Binary Search Tree"},
        {"q": "What is the principle of inheritance?", "options": ["Deleting older classes", "Creating a new class based on an existing class", "Combining multiple projects", "Hiding variables"], "answer": "Creating a new class based on an existing class"}
    ],
    "Data Scientist": [
        {"q": "In probability, what does Bayes' Theorem calculate?", "options": ["Standard Deviation", "Posterior Probability", "Expected Value", "Variance"], "answer": "Posterior Probability"},
        {"q": "Which normal form in DBMS deals with removing transitive dependencies?", "options": ["1NF", "2NF", "3NF", "BCNF"], "answer": "3NF"},
        {"q": "What does a p-value indicate?", "options": ["The probability of observing the data given the null hypothesis is true", "The probability that the alternative hypothesis is true", "The variance of the sample", "The margin of error"], "answer": "The probability of observing the data given the null hypothesis is true"},
        {"q": "Which of these is a measure of dispersion?", "options": ["Mean", "Median", "Mode", "Variance"], "answer": "Variance"},
        {"q": "What is Principal Component Analysis (PCA) primary used for?", "options": ["Classification", "Regression", "Dimensionality Reduction", "Clustering"], "answer": "Dimensionality Reduction"},
        {"q": "In SQL, what does the GROUP BY clause do?", "options": ["Orders the results alphabetically", "Filters rows before aggregation", "Groups rows with identical values into summary rows", "Joins two tables"], "answer": "Groups rows with identical values into summary rows"},
        {"q": "What type of distribution is described by a bell curve?", "options": ["Binomial", "Poisson", "Normal", "Uniform"], "answer": "Normal"},
        {"q": "What is linear regression used for?", "options": ["Categorizing items", "Predicting a continuous numerical value", "Selecting features", "Cleaning data"], "answer": "Predicting a continuous numerical value"},
        {"q": "In matrices, what is the determinant?", "options": ["The number of columns", "A scalar value computed from the elements of a square matrix", "The inverse of a matrix", "The sum of diagonal elements"], "answer": "A scalar value computed from the elements of a square matrix"},
        {"q": "What does an SQL JOIN do?", "options": ["Combines rows from two or more tables", "Deletes redundant data", "Creates a new table", "Validates constraints"], "answer": "Combines rows from two or more tables"},
        {"q": "What is an outlier?", "options": ["A missing value", "A data point that differs significantly from other observations", "The most frequent value", "A normalized feature"], "answer": "A data point that differs significantly from other observations"},
        {"q": "What is correlation?", "options": ["A measure of cause and effect", "A measure of the extent to which two variables are linearly related", "The difference between variables", "The spread of a single variable"], "answer": "A measure of the extent to which two variables are linearly related"},
        {"q": "Which command retrieves data from a database?", "options": ["SELECT", "UPDATE", "INSERT", "FETCH"], "answer": "SELECT"},
        {"q": "In statistics, what is the mode?", "options": ["The average value", "The middle value", "The value that appears most frequently", "The largest value"], "answer": "The value that appears most frequently"},
        {"q": "What is the purpose of regularization in machine learning?", "options": ["To speed up training", "To increase model complexity", "To prevent overfitting", "To prepare data for input"], "answer": "To prevent overfitting"},
        {"q": "What does a confusion matrix evaluate?", "options": ["Clustering accuracy", "The performance of a classification model", "Data quality", "Regression error"], "answer": "The performance of a classification model"},
        {"q": "What is an INNER JOIN?", "options": ["Returns all records from the left table", "Returns records holding matching values in both tables", "Returns all records from both tables", "Cartesian product of tables"], "answer": "Returns records holding matching values in both tables"},
        {"q": "The Central Limit Theorem primarily applies to:", "options": ["Sample medians", "Sample means", "Variances", "Outliers"], "answer": "Sample means"},
        {"q": "What is logistic regression primarily used for?", "options": ["Binary classification", "Continuous prediction", "Clustering", "Dimensionality reduction"], "answer": "Binary classification"},
        {"q": "What defines a primary key?", "options": ["A column that allows nulls", "A unique identifier for a row in a table", "A reference to another table", "An indexed column"], "answer": "A unique identifier for a row in a table"}
    ],
    "Cybersecurity": [
        {"q": "At which OSI layer does a network switch primarily operate?", "options": ["Physical", "Data Link", "Network", "Transport"], "answer": "Data Link"},
        {"q": "Which type of attack involves intercepting communication between two parties?", "options": ["Phishing", "Man-in-the-Middle", "DDoS", "SQL Injection"], "answer": "Man-in-the-Middle"},
        {"q": "What cryptographic protocol is most commonly used by HTTPS?", "options": ["TLS/SSL", "WEP", "SSH", "FTP"], "answer": "TLS/SSL"},
        {"q": "What is a firewall?", "options": ["A virus scanner", "A network security system monitoring traffic", "An encryption tool", "A password manager"], "answer": "A network security system monitoring traffic"},
        {"q": "Which attack overwhelms a target server with traffic?", "options": ["SQLi", "XSS", "DDoS", "Ransomware"], "answer": "DDoS"},
        {"q": "What does phishing primarily involve?", "options": ["Guessing passwords", "Sending fraudulent communications appearing reputable", "Exploiting buffer overflows", "Scanning ports"], "answer": "Sending fraudulent communications appearing reputable"},
        {"q": "Which of these is a widely-used symmetric encryption algorithm?", "options": ["RSA", "DSA", "AES", "SHA-256"], "answer": "AES"},
        {"q": "What is the main purpose of a VPN?", "options": ["To speed up internet", "To create a secure, encrypted connection over a network", "To host a website", "To block ads"], "answer": "To create a secure, encrypted connection over a network"},
        {"q": "What is a botnet?", "options": ["A network of compromised computers controlled by an attacker", "A helpful AI assistant", "A secure private network", "A firewall configuration"], "answer": "A network of compromised computers controlled by an attacker"},
        {"q": "At which OSI layer does the Internet Protocol (IP) operate?", "options": ["Data Link", "Network", "Transport", "Application"], "answer": "Network"},
        {"q": "What is port scanning used for?", "options": ["Encrypting data", "Probing a server or host for open ports", "Sending emails", "Compiling code"], "answer": "Probing a server or host for open ports"},
        {"q": "What security principle does hashing primarily provide?", "options": ["Confidentiality", "Availability", "Integrity", "Accountability"], "answer": "Integrity"},
        {"q": "Which protocol translates domain names to IP addresses?", "options": ["DHCP", "DNS", "HTTP", "ARP"], "answer": "DNS"},
        {"q": "What is social engineering?", "options": ["Designing software", "Manipulating people into yielding confidential info", "Building secure networks", "Encrypting databases"], "answer": "Manipulating people into yielding confidential info"},
        {"q": "What is malware?", "options": ["Defective hardware", "Software created to cause damage to a computer or network", "An operating system", "A programming language"], "answer": "Software created to cause damage to a computer or network"},
        {"q": "What describes a zero-day vulnerability?", "options": ["A fixed bug", "A flaw unknown to the vendor with no patch yet", "A feature of an OS", "A weak password"], "answer": "A flaw unknown to the vendor with no patch yet"},
        {"q": "Which port is standard for SSH connections?", "options": ["21", "22", "80", "443"], "answer": "22"},
        {"q": "What is the principle of least privilege?", "options": ["Everyone gets admin access", "Giving a user only the minimum access needed for their job", "Using the weakest encryption", "Avoiding firewalls"], "answer": "Giving a user only the minimum access needed for their job"},
        {"q": "What does IDS stand for in security?", "options": ["Internal Data Storage", "Intrusion Detection System", "Internet Domain Service", "Integrated Defense Security"], "answer": "Intrusion Detection System"},
        {"q": "Which personal wireless security protocol is currently considered most secure?", "options": ["WEP", "WPA", "WPA2", "WPA3"], "answer": "WPA3"}
    ],
    "AI/ML Engineer": [
        {"q": "Which activation function is most commonly used in the hidden layers of a Convolutional Neural Network?", "options": ["Sigmoid", "Tanh", "ReLU", "Softmax"], "answer": "ReLU"},
        {"q": "What is the primary purpose of dropout in neural networks?", "options": ["Increase training speed", "Prevent overfitting", "Reduce dataset size", "Handle missing values"], "answer": "Prevent overfitting"},
        {"q": "Which algorithm is standard for training deep neural networks?", "options": ["A* Search", "Backpropagation", "K-Means", "Merge Sort"], "answer": "Backpropagation"},
        {"q": "What is a hyperparameter?", "options": ["A parameter learned during training", "A parameter set before the learning process begins", "The final accuracy score", "The input data size"], "answer": "A parameter set before the learning process begins"},
        {"q": "Which loss function is typically used for binary classification?", "options": ["Mean Squared Error", "Categorical Cross-Entropy", "Binary Cross-Entropy", "Huber Loss"], "answer": "Binary Cross-Entropy"},
        {"q": "In NLP, what does TF-IDF stand for?", "options": ["Text Frequency-Inverse Data Frequency", "Term Frequency-Inverse Document Frequency", "Token Format-Index Document Format", "Text Factor-Inverse Distribution Factor"], "answer": "Term Frequency-Inverse Document Frequency"},
        {"q": "In linear algebra, what is a vector?", "options": ["A single number", "An array of numbers with magnitude and direction", "A massive dataset", "A string of text"], "answer": "An array of numbers with magnitude and direction"},
        {"q": "Which of the following is an unsupervised learning algorithm?", "options": ["Linear Regression", "Logistic Regression", "K-Means Clustering", "Support Vector Machines"], "answer": "K-Means Clustering"},
        {"q": "What type of data does a Recurrent Neural Network (RNN) excel at processing?", "options": ["Images", "Audio", "Sequential data", "Tabular data"], "answer": "Sequential data"},
        {"q": "What does an 'epoch' refer to in training?", "options": ["One forward pass", "One complete pass of the entire training dataset", "One batch of data", "One parameter update"], "answer": "One complete pass of the entire training dataset"},
        {"q": "In gradient descent, what is the gradient?", "options": ["The loss value", "The derivative indicating direction of steepest ascent", "The learning rate", "The final weight"], "answer": "The derivative indicating direction of steepest ascent"},
        {"q": "Which neural architecture is famous for pioneering self-attention mechanisms?", "options": ["CNN", "RNN", "Transformer", "GAN"], "answer": "Transformer"},
        {"q": "What is data augmentation?", "options": ["Deleting bad data", "Generating new training instances by altering existing ones", "Scaling data", "Downloading more datasets"], "answer": "Generating new training instances by altering existing ones"},
        {"q": "In reinforcement learning, what is the reward?", "options": ["A scalar feedback signal evaluating performance", "The final learned weights", "The exploration rate", "The predicted class"], "answer": "A scalar feedback signal evaluating performance"},
        {"q": "What is cross-validation used for?", "options": ["Cleaning data", "Assessing how accurately a model will generalize to new data", "Training a neural network", "Generating features"], "answer": "Assessing how accurately a model will generalize to new data"},
        {"q": "What is the learning rate?", "options": ["How fast the CPU runs", "The step size taken at each iteration toward a minimum", "The number of epochs", "The size of the dataset"], "answer": "The step size taken at each iteration toward a minimum"},
        {"q": "What is transfer learning?", "options": ["Moving data to a new server", "Reusing a pre-trained model as a starting point for a new task", "Training multiple models", "Translating code"], "answer": "Reusing a pre-trained model as a starting point for a new task"},
        {"q": "What is an eigenvalue?", "options": ["A random weight", "A scalar indicating how an eigenvector is scaled under transformation", "A loss metric", "A type of layer"], "answer": "A scalar indicating how an eigenvector is scaled under transformation"},
        {"q": "Which technique is commonly used to handle exploding gradients?", "options": ["Gradient clipping", "Increasing learning rate", "Removing hidden layers", "Adding more data"], "answer": "Gradient clipping"},
        {"q": "What is the softmax function primarily used for?", "options": ["Activating hidden layers", "Converting a vector of raw scores into a probability distribution", "Calculating loss", "Initializing weights"], "answer": "Converting a vector of raw scores into a probability distribution"}
    ],
    "General IT": [
        {"q": "Which of the following is a non-volatile memory?", "options": ["RAM", "ROM", "Cache", "Register"], "answer": "ROM"},
        {"q": "What is a primary key in a relational database?", "options": ["A key that allows null values", "A unique identifier for a record", "A key used to encrypt data", "A foreign key reference"], "answer": "A unique identifier for a record"},
        {"q": "What does CPU stand for?", "options": ["Computer Processing Unit", "Central Performance Unit", "Central Processing Unit", "Control Processing Unit"], "answer": "Central Processing Unit"},
        {"q": "Which of these is an example of an Operating System?", "options": ["Microsoft Word", "Google Chrome", "Linux", "Python"], "answer": "Linux"},
        {"q": "What does IP stand for in networking?", "options": ["Internet Protocol", "Internal Process", "Information Provider", "Internet Path"], "answer": "Internet Protocol"},
        {"q": "Which command line utility checks network connectivity?", "options": ["ipconfig", "ping", "dir", "mkdir"], "answer": "ping"},
        {"q": "What technology does an SSD use to store data?", "options": ["Magnetic disks", "Optical lasers", "Flash memory", "Punch cards"], "answer": "Flash memory"},
        {"q": "What essentially is \"the cloud\"?", "options": ["Weather phenomena", "Servers and services accessed over the internet", "A type of physical hard drive", "A new operating system"], "answer": "Servers and services accessed over the internet"},
        {"q": "What does GUI stand for?", "options": ["General User Interface", "Graphical User Interface", "Global User Index", "General Utility Interface"], "answer": "Graphical User Interface"},
        {"q": "Which of the following is a Version Control System?", "options": ["Docker", "Git", "Jenkins", "Kubernetes"], "answer": "Git"},
        {"q": "What is a domain name?", "options": ["An IP address", "A physical server location", "A human-readable text address for a website", "A type of network switch"], "answer": "A human-readable text address for a website"},
        {"q": "Which protocol is typically used for sending email?", "options": ["HTTP", "FTP", "SMTP", "SSH"], "answer": "SMTP"},
        {"q": "What does API stand for?", "options": ["Application Programming Interface", "Automated Program Interface", "Application Process Integration", "Authorized Programming Index"], "answer": "Application Programming Interface"},
        {"q": "What is an IDE?", "options": ["Internal Drive Extension", "Integrated Development Environment", "Internet Domain Entity", "Interactive Design Element"], "answer": "Integrated Development Environment"},
        {"q": "What is the primary role of HTML?", "options": ["Styling elements", "Structuring web pages", "Executing server logic", "Database management"], "answer": "Structuring web pages"},
        {"q": "What is a MAC address?", "options": ["An Apple computer name", "A unique hardware identifier for a network interface", "An IP address assigned by router", "A software license mark"], "answer": "A unique hardware identifier for a network interface"},
        {"q": "Which of the following is an open-source software license?", "options": ["Windows EULA", "GPL (General Public License)", "Adobe Creative Cloud", "Apple iOS License"], "answer": "GPL (General Public License)"},
        {"q": "What is the primary function of a network router?", "options": ["Store files", "Forward data packets between computer networks", "Display graphics", "Compile code"], "answer": "Forward data packets between computer networks"},
        {"q": "What is virtual memory?", "options": ["Memory used in VR headsets", "A management technique using disk space as extended RAM", "Cloud storage", "Cache memory"], "answer": "A management technique using disk space as extended RAM"},
        {"q": "What is a software bug?", "options": ["A computer virus", "A flaw or error in a computer program that causes unexpected results", "A hardware failure", "A network intrusion"], "answer": "A flaw or error in a computer program that causes unexpected results"}
    ]
}
