ROADMAP_DATA = {
    "software": [
        # Roadmap 1: Backend focus
        [
            {"week": "Week 1: Fundamentals", "goal": "Core CS Concepts & Control Flow", "resources": ["[CS50](https://cs50.harvard.edu)", "[Codecademy](https://www.codecademy.com)", "[LeetCode Array Basics](https://leetcode.com)"]},
            {"week": "Week 2: Backend Basics", "goal": "APIs and Server Architecture", "resources": ["[FreeCodeCamp APIs](https://www.freecodecamp.org/news/apis-for-beginners/)", "[MDN Server Tech](https://developer.mozilla.org/)", "[Postman Tutorial](https://www.postman.com/)"]},
            {"week": "Week 3: Databases (SQL)", "goal": "Relational Data Modeling", "resources": ["[SQL Zoo](https://sqlzoo.net/)", "[PostgreSQL Tutorial](https://www.postgresqltutorial.com/)", "[W3Schools SQL](https://www.w3schools.com/sql/)"]},
            {"week": "Week 4: Databases (NoSQL)", "goal": "Document Stores", "resources": ["[MongoDB University](https://learn.mongodb.com/)", "[Firebase Docs](https://firebase.google.com/docs/)", "[NoSQL Concepts](https://aws.amazon.com/nosql/)"]},
            {"week": "Week 5: Framework Deep Dive", "goal": "Node/Express or Django/Spring", "resources": ["[Express Docs](https://expressjs.com/)", "[Django Tutorial](https://docs.djangoproject.com/)", "[Spring Boot Basics](https://spring.io/projects/spring-boot)"]},
            {"week": "Week 6: Midterm Project", "goal": "Build a fully functional REST API", "resources": ["[GitHub REST Guidelines](https://docs.github.com/en/rest)", "[REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)", "[Project Ideas](https://github.com/florinpop17/app-ideas)"]},
            {"week": "Week 7: Authentication & Security", "goal": "JWT, OAuth, CORS", "resources": ["[JWT.io](https://jwt.io/)", "[OAuth 2.0 Docs](https://oauth.net/2/)", "[OWASP Top 10](https://owasp.org/)"]},
            {"week": "Week 8: Caching & Performance", "goal": "Redis, Memcached", "resources": ["[Redis Crash Course](https://redis.io/)", "[System Design Caching](https://github.com/donnemartin/system-design-primer)", "[Performance Tuning](https://web.dev/)"]},
            {"week": "Week 9: Containerization", "goal": "Docker & Docker Compose", "resources": ["[Docker 101](https://www.docker.com/101-tutorial/)", "[Play with Docker](https://labs.play-with-docker.com/)", "[Container Concepts](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/)"]},
            {"week": "Week 10: CI/CD & Deployment", "goal": "GitHub Actions & AWS/Heroku", "resources": ["[GitHub Actions Guide](https://docs.github.com/en/actions)", "[AWS EC2 Setup](https://aws.amazon.com/ec2/)", "[Render Docs](https://render.com/docs)"]}
        ],
        # Roadmap 2: Systems focus
        [
            {"week": "Week 1: C/C++ Refresher", "goal": "Pointers and Memory Management", "resources": ["[LearnCpp](https://www.learncpp.com/)", "[C Programming Basics](https://www.cprogramming.com/)", "[Valgrind Docs](https://valgrind.org/)"]},
            {"week": "Week 2: OS Fundamentals", "goal": "Processes, Threads, and Concurrency", "resources": ["[OS Three Easy Pieces](https://pages.cs.wisc.edu/~remzi/OSTEP/)", "[Concurrency in C](https://en.cppreference.com/)", "[MIT 6.828](https://pdos.csail.mit.edu/6.828/)"]},
            {"week": "Week 3: Advanced Data Structures", "goal": "Trees, Graphs, and Hashmaps", "resources": ["[GeeksforGeeks Advanced](https://www.geeksforgeeks.org/advanced-data-structures/)", "[Visualgo](https://visualgo.net/)", "[LeetCode Graphs](https://leetcode.com/)"]},
            {"week": "Week 4: System Level Networking", "goal": "Sockets, TCP/IP", "resources": ["[Beej's Guide](https://beej.us/guide/bgnet/)", "[Network Topologies](https://www.cisco.com/)", "[Wireshark Tutorial](https://www.wireshark.org/)"]},
            {"week": "Week 5: I/O and File Systems", "goal": "Deep dive into storage logic", "resources": ["[Linux File System](https://tldp.org/)", "[Ext4 Docs](https://ext4.wiki.kernel.org/)", "[I/O Performance](https://lwn.net/)"]},
            {"week": "Week 6: System Project", "goal": "Build a multi-threaded web server from scratch", "resources": ["[Let's Build a Web Server](https://ruslanspivak.com/lsbaws-part1/)", "[Posix Threads](https://computing.llnl.gov/tutorials/pthreads/)", "[C Socket Programming](https://www.geeksforgeeks.org/)"]},
            {"week": "Week 7: Embedded Systems Basics", "goal": "Microcontrollers and RTOS", "resources": ["[Arduino Docs](https://www.arduino.cc/)", "[FreeRTOS Guide](https://www.freertos.org/)", "[Embedded C](https://www.coursera.org/specializations/embedded-systems)"]},
            {"week": "Week 8: Performance Profiling", "goal": "Optimizing at the assembly level", "resources": ["[GDB Tutorial](https://www.gnu.org/software/gdb/)", "[Compiler Explorer](https://godbolt.org/)", "[Assembly Basics](https://www.tutorialspoint.com/assembly_programming/)"]},
            {"week": "Week 9: Distributed Systems Concepts", "goal": "CAP Theorem, Consensus", "resources": ["[Distributed Systems (Maarten van Steen)](https://www.distributed-systems.net/)", "[Raft Consensus](https://raft.github.io/)", "[Martin Fowler DS](https://martinfowler.com/)"]},
            {"week": "Week 10: Final Systems Integration", "goal": "Deploy and test scalable low-level modules", "resources": ["[Testing Distributed Systems](https://aphyr.com/)", "[Jepsen Reports](https://jepsen.io/)", "[Scale Architecture](https://highscalability.com/)"]}
        ],
        # Roadmap 3: Generalist Software Engineer
        [
            {"week": "Week 1: Clean Code Principles", "goal": "SOLID, DRY, KISS", "resources": ["[Refactoring Guru](https://refactoring.guru/)", "[Clean Code Digest](https://github.com/ryanmcdermott/clean-code-javascript)", "[Code Smells](https://blog.codinghorror.com/)"]},
            {"week": "Week 2: Front-End Basics", "goal": "DOM Manipulation and Events", "resources": ["[MDN Web Docs](https://developer.mozilla.org/)", "[JavaScript Info](https://javascript.info/)", "[CSS Tricks](https://css-tricks.com/)"]},
            {"week": "Week 3: Back-End Basics", "goal": "API Design and Setup", "resources": ["[REST API Tutorial](https://restfulapi.net/)", "[Postman Learn](https://learning.postman.com/)", "[Node.js Org](https://nodejs.org/)"]},
            {"week": "Week 4: Database Integration", "goal": "Connecting Frontend to Backend via DB", "resources": ["[Full Stack Open](https://fullstackopen.com/)", "[Prisma Docs](https://www.prisma.io/)", "[SQL Constraints](https://www.w3schools.com/sql/)"]},
            {"week": "Week 5: TDD & Unit Testing", "goal": "Writing robust tests before logic", "resources": ["[Jest Crash Course](https://jestjs.io/)", "[Pytest Guides](https://docs.pytest.org/)", "[TDD Rules](https://martinfowler.com/bliki/TestDrivenDevelopment.html)"]},
            {"week": "Week 6: Mid-Point Full Stack App", "goal": "Build a CRUD application", "resources": ["[CRUD Example Guide](https://www.freecodecamp.org/)", "[GitHub Actions](https://docs.github.com/)", "[Frontend Mentor](https://www.frontendmentor.io/)"]},
            {"week": "Week 7: Version Control Workflows", "goal": "Git Flow and Agile Sprints", "resources": ["[Atlassian Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows)", "[Scrum Guide](https://scrumguides.org/)", "[Jira Basics](https://www.atlassian.com/software/jira)"]},
            {"week": "Week 8: Systems Design Primer", "goal": "High-level architecture choices", "resources": ["[System Design Primer](https://github.com/donnemartin/system-design-primer)", "[ByteByteGo](https://www.youtube.com/@ByteByteGo)", "[Scalability Principles](https://aws.amazon.com/architecture/)"]},
            {"week": "Week 9: Refactoring & Legacy Code", "goal": "How to update old codebases", "resources": ["[Working Effectively with Legacy Code](https://understandlegacycode.com/)", "[Refactoring Best Practices](https://sourcemaking.com/)", "[Code Review Guide](https://google.github.io/eng-practices/review/reviewer/)"]},
            {"week": "Week 10: Production & Analytics", "goal": "Launch and monitor", "resources": ["[Vercel Analytics](https://vercel.com/docs/analytics)", "[Sentry Error Tracking](https://sentry.io/)", "[Google Analytics setup](https://analytics.google.com/)"]}
        ],
        # Roadmap 4: Cloud Focus
        [
            {"week": "Week 1: Cloud Linux & Networking", "goal": "VPCs, Subnets, Shell Scripting", "resources": ["[AWS VPC Guide](https://docs.aws.amazon.com/vpc/)", "[Linux Command Line](https://ubuntu.com/tutorials/command-line-for-beginners)", "[CIDR Basics](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)"]},
            {"week": "Week 2: Core Cloud Compute", "goal": "EC2, VMs, and Auto Scaling", "resources": ["[AWS EC2 Intro](https://aws.amazon.com/ec2/)", "[Azure Virtual Machines](https://azure.microsoft.com/)", "[GCP Compute Engine](https://cloud.google.com/compute)"]},
            {"week": "Week 3: Serverless Functions", "goal": "AWS Lambda, Event-driven architecture", "resources": ["[Serverless Framework](https://www.serverless.com/)", "[AWS Lambda Docs](https://docs.aws.amazon.com/lambda/)", "[Cloud Functions](https://cloud.google.com/functions)"]},
            {"week": "Week 4: Cloud Databases", "goal": "RDS, DynamoDB, managed services", "resources": ["[DynamoDB Core Concepts](https://docs.aws.amazon.com/amazondynamodb/)", "[Managed Relational DBs](https://aws.amazon.com/rds/)", "[Firestore Guide](https://firebase.google.com/docs/firestore)"]},
            {"week": "Week 5: Cloud Storage & CDN", "goal": "S3, CloudFront, Edge routing", "resources": ["[S3 Best Practices](https://aws.amazon.com/s3/)", "[Cloudflare CDN](https://www.cloudflare.com/)", "[AWS CloudFront](https://aws.amazon.com/cloudfront/)"]},
            {"week": "Week 6: Infrastructure as Code", "goal": "Terraform and CloudFormation", "resources": ["[HashiCorp Terraform Tutorial](https://learn.hashicorp.com/terraform)", "[AWS CloudFormation Docs](https://aws.amazon.com/cloudformation/)", "[Ansible Basics](https://www.ansible.com/)"]},
            {"week": "Week 7: Container Orchestration", "goal": "Kubernetes Clusters (EKS/GKE)", "resources": ["[Kubernetes Basics](https://kubernetes.io/docs/tutorials/kubernetes-basics/)", "[AWS EKS](https://aws.amazon.com/eks/)", "[Docker Swarm vs K8s](https://www.docker.com/)"]},
            {"week": "Week 8: Cloud Security & IAM", "goal": "Permissions, Policies, and Roles", "resources": ["[AWS IAM Documentation](https://docs.aws.amazon.com/iam/)", "[Zero Trust Security](https://www.crowdstrike.com/)", "[Auth0 Cloud Security](https://auth0.com/)"]},
            {"week": "Week 9: Monitoring & Observability", "goal": "CloudWatch, Datadog, Prometheus", "resources": ["[Prometheus Monitoring](https://prometheus.io/)", "[Datadog HQ](https://www.datadoghq.com/)", "[Grafana Dashboards](https://grafana.com/)"]},
            {"week": "Week 10: Capstone Cloud Migration", "goal": "Migrate a monolithic app to microservices", "resources": ["[Microservices Pattern](https://microservices.io/)", "[AWS Migration Hub](https://aws.amazon.com/migration-hub/)", "[Strangler Fig Pattern](https://martinfowler.com/bliki/StranglerFigApplication.html)"]}
        ]
    ],
    "ai": [
        # Roadmap 1: Machine Learning Engineer
        [
            {"week": "Week 1: Math Foundation", "goal": "Linear Algebra & Calculus", "resources": ["[3Blue1Brown LinAlg](https://www.3blue1brown.com/)", "[Khan Academy Calculus](https://www.khanacademy.org/)", "[Math for ML Book](https://mml-book.github.io/)"]},
            {"week": "Week 2: Advanced Data Manipulation", "goal": "Pandas & NumPy Mastery", "resources": ["[Pandas User Guide](https://pandas.pydata.org/docs/)", "[NumPy Tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)", "[Kaggle Python Course](https://www.kaggle.com/learn/python)"]},
            {"week": "Week 3: Classical ML Algorithms", "goal": "Regression, Classification, Clustering", "resources": ["[Scikit-Learn Docs](https://scikit-learn.org/stable/)", "[Andrew Ng ML Course](https://www.coursera.org/specializations/machine-learning-introduction)", "[StatQuest YouTube](https://www.youtube.com/@statquest)"]},
            {"week": "Week 4: Feature Engineering", "goal": "Data Cleaning & Prep", "resources": ["[Feature Engineering Kaggle](https://www.kaggle.com/learn/feature-engineering)", "[Towards Data Science](https://towardsdatascience.com/)", "[Google Data Prep](https://developers.google.com/machine-learning/crash-course/)"]},
            {"week": "Week 5: Deep Learning Foundations", "goal": "Neural Networks basics in PyTorch/TF", "resources": ["[PyTorch Tutorials](https://pytorch.org/tutorials/)", "[TensorFlow Basics](https://www.tensorflow.org/tutorials)", "[DeepLearning.AI](https://www.deeplearning.ai/)"]},
            {"week": "Week 6: Computer Vision", "goal": "CNNs, Image Classification", "resources": ["[CS231n Stanford](http://cs231n.stanford.edu/)", "[Albumentations](https://albumentations.ai/)", "[OpenCV Python](https://opencv.org/)"]},
            {"week": "Week 7: Natural Language Processing", "goal": "RNNs, Embeddings, Text Processing", "resources": ["[Hugging Face Course](https://huggingface.co/course/chapter1/1)", "[NLTK Book](https://www.nltk.org/book/)", "[Spacy NLP](https://spacy.io/)"]},
            {"week": "Week 8: Transformers & LLMs", "goal": "Attention mechanism, fine-tuning", "resources": ["[Attention is All You Need](https://arxiv.org/abs/1706.03762)", "[Hugging Face Transformers](https://huggingface.co/docs/transformers/)", "[LangChain Docs](https://python.langchain.com/)"]},
            {"week": "Week 9: MLOps & Model Deployment", "goal": "Serving models in production", "resources": ["[MLOps Org](https://mlops.org/)", "[FastAPI Model Serving](https://fastapi.tiangolo.com/)", "[TFX Guide](https://www.tensorflow.org/tfx)"]},
            {"week": "Week 10: Capstone AI Project", "goal": "End-to-End ML Pipeline", "resources": ["[Weights & Biases](https://wandb.ai/)", "[Streamlit Deploy](https://streamlit.io/)", "[Gradio Interfaces](https://gradio.app/)"]}
        ],
        # Roadmap 2: Prompt Engineering & Generative AI
        [
            {"week": "Week 1: GenAI Overview", "goal": "Understanding LLMs and API ecosystem", "resources": ["[OpenAI Docs](https://platform.openai.com/docs/)", "[Google Gemini API](https://ai.google.dev/)", "[Anthropic Claude](https://www.anthropic.com/)"]},
            {"week": "Week 2: Prompting Basics", "goal": "Zero-shot, Few-shot, Chain-of-Thought", "resources": ["[Prompting Guide](https://www.promptingguide.ai/)", "[Learn Prompting](https://learnprompting.org/)", "[OpenAI Cookbook](https://cookbook.openai.com/)"]},
            {"week": "Week 3: Advanced Prompting", "goal": "ReAct, Tree of Thoughts, Persona engineering", "resources": ["[LangChain ReAct](https://python.langchain.com/)", "[Semantic Kernel](https://github.com/microsoft/semantic-kernel)", "[Best Practices LLM](https://www.deeplearning.ai/)"]},
            {"week": "Week 4: Retrieval Augmented Generation (RAG)", "goal": "Vector DBs and Embeddings", "resources": ["[Pinecone Docs](https://docs.pinecone.io/)", "[ChromaDB Start](https://docs.trychroma.com/)", "[Weaviate Vector DB](https://weaviate.io/)"]},
            {"week": "Week 5: Building AI Agents", "goal": "Tool use and API integration via LLMs", "resources": ["[AutoGPT GitHub](https://github.com/Significant-Gravitas/AutoGPT)", "[LangChain Agents](https://python.langchain.com/)", "[LlamaIndex](https://www.llamaindex.ai/)"]},
            {"week": "Week 6: Evaluating LLM Outputs", "goal": "RAGAS, similarity metrics, hallucination checks", "resources": ["[RAGAS Framework](https://docs.ragas.io/en/latest/)", "[TruLens Eval](https://www.trulens.org/)", "[OpenAI Evals](https://github.com/openai/evals)"]},
            {"week": "Week 7: Open Source Models", "goal": "Llama 3, Mistral, Ollama setup", "resources": ["[Ollama Local LLM](https://ollama.com/)", "[Hugging Face Hub](https://huggingface.co/)", "[LM Studio](https://lmstudio.ai/)"]},
            {"week": "Week 8: Fine-tuning Basics", "goal": "LoRA, PEFT, Dataset Preparation", "resources": ["[PEFT Documentation](https://huggingface.co/docs/peft)", "[LoRA Explained](https://arxiv.org/abs/2106.09685)", "[Axolotl Fine-Tuning](https://github.com/OpenAccess-AI-Collective/axolotl)"]},
            {"week": "Week 9: Guardrails & Safety", "goal": "Output parsing, bias mitigation", "resources": ["[Nvidia NeMo Guardrails](https://github.com/NVIDIA/NeMo-Guardrails)", "[LangChain Output Parsers](https://python.langchain.com/)", "[AI Safety Guidelines](https://www.alignmentforum.org/)"]},
            {"week": "Week 10: AI Application Delivery", "goal": "Deploy a chat agent with UI", "resources": ["[Streamlit for GenAI](https://docs.streamlit.io/)", "[Vercel AI SDK](https://sdk.vercel.ai/docs)", "[Supabase pgvector](https://supabase.com/docs/guides/ai)"]}
        ]
    ],
    "data": [
        # Roadmap 1: Data Analytics
        [
            {"week": "Week 1: Excel Mastery", "goal": "VLOOKUP, Pivot Tables, Macros", "resources": ["[Excel Easy](https://www.excel-easy.com/)", "[MrExcel](https://www.mrexcel.com/)", "[Coursera Excel](https://www.coursera.org/)"]},
            {"week": "Week 2: SQL Basics", "goal": "Selects, Joins, Group By", "resources": ["[Mode SQL Tutorial](https://mode.com/sql-tutorial/)", "[SQLBolt](https://sqlbolt.com/)", "[W3Schools SQL](https://www.w3schools.com/sql/)"]},
            {"week": "Week 3: Advanced SQL", "goal": "Window functions, CTEs", "resources": ["[PostgreSQL Window Functions](https://www.postgresqltutorial.com/)", "[Advanced SQL (Kaggle)](https://www.kaggle.com/learn/advanced-sql)", "[LeetCode Database](https://leetcode.com/)"]},
            {"week": "Week 4: BI Tools (Tableau/PowerBI)", "goal": "Building visually appealing dashboards", "resources": ["[Tableau Public](https://public.tableau.com/)", "[PowerBI Learning Paths](https://learn.microsoft.com/en-us/power-bi/)", "[DataViz Catalogue](https://datavizcatalogue.com/)"]},
            {"week": "Week 5: Python for Data", "goal": "Pandas, Matplotlib", "resources": ["[Pandas Docs](https://pandas.pydata.org/)", "[Matplotlib Gallery](https://matplotlib.org/)", "[Seaborn Tutorial](https://seaborn.pydata.org/)"]},
            {"week": "Week 6: Exploratory Data Analysis", "goal": "Outliers, missing data, correlation", "resources": ["[Kaggle EDA](https://www.kaggle.com/)", "[Towards Data Science EDA](https://towardsdatascience.com/)", "[StatsQuest](https://www.youtube.com/@statquest)"]},
            {"week": "Week 7: Statistical Analysis", "goal": "A/B Testing, Hypothesis Testing", "resources": ["[Khan Academy Stats](https://www.khanacademy.org/math/statistics-probability)", "[A/B Testing Guide](https://vwo.com/ab-testing/)", "[Scipy Stats Module](https://docs.scipy.org/doc/scipy/reference/stats.html)"]},
            {"week": "Week 8: Storytelling with Data", "goal": "Presenting insights to stakeholders", "resources": ["[Storytelling with Data Book](https://www.storytellingwithdata.com/)", "[Information is Beautiful](https://informationisbeautiful.net/)", "[Harvard Business Data](https://hbr.org/)"]},
            {"week": "Week 9: Predictive Analysis", "goal": "Basic Linear Regression & Forecasting", "resources": ["[Scikit-Learn Linear Models](https://scikit-learn.org/)", "[Forecasting Principles](https://otexts.com/fpp2/)", "[Prophet by Meta](https://facebook.github.io/prophet/)"]},
            {"week": "Week 10: End-to-End Analytics Project", "goal": "Scrape, Clean, Analyze, and Dashboard", "resources": ["[BeautifulSoup Docs](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)", "[Kaggle Datasets](https://www.kaggle.com/datasets)", "[GitHub Pages Hosting](https://pages.github.com/)"]}
        ],
        # Roadmap 2: Data Engineering
        [
            {"week": "Week 1: Python/Scala Coding", "goal": "Functional programming and scripts", "resources": ["[Python Functional](https://docs.python.org/3/howto/functional.html)", "[Scala Tour](https://docs.scala-lang.org/tour/tour-of-scala.html)", "[HackerRank Python](https://www.hackerrank.com/)"]},
            {"week": "Week 2: Relational Databases Architecture", "goal": "Indexing, Execution Plans", "resources": ["[Use The Index Luke](https://use-the-index-luke.com/)", "[PostgreSQL Internals](https://www.postgresql.org/docs/)", "[Database Normalization](https://en.wikipedia.org/wiki/Database_normalization)"]},
            {"week": "Week 3: Data Warehouses", "goal": "Snowflake, BigQuery, Redshift schemas", "resources": ["[Kimball Methodology](https://www.kimballgroup.com/)", "[Snowflake Docs](https://docs.snowflake.com/)", "[Google BigQuery](https://cloud.google.com/bigquery)"]},
            {"week": "Week 4: ETL & Pipeline Orchestration", "goal": "Apache Airflow, Prefect, Dagster", "resources": ["[Airflow Tutorial](https://airflow.apache.org/docs/apache-airflow/stable/tutorial/index.html)", "[Prefect Docs](https://docs.prefect.io/)", "[Dagster Univ](https://courses.dagster.io/)"]},
            {"week": "Week 5: Distributed Data Processing", "goal": "Apache Spark & MapReduce", "resources": ["[Spark Documentation](https://spark.apache.org/docs/latest/)", "[PySpark Tutorial](https://spark.apache.org/docs/latest/api/python/)", "[Databricks Academy](https://www.databricks.com/)"]},
            {"week": "Week 6: Event Streaming & Real-time", "goal": "Apache Kafka, Flink, Pub/Sub", "resources": ["[Kafka Quickstart](https://kafka.apache.org/quickstart)", "[Confluent Developer](https://developer.confluent.io/)", "[Apache Flink](https://flink.apache.org/)"]},
            {"week": "Week 7: Cloud Data Lakes", "goal": "S3, Azure Data Lake, Parquet/Iceberg formats", "resources": ["[Apache Iceberg](https://iceberg.apache.org/)", "[Parquet Format](https://parquet.apache.org/)", "[AWS Lake Formation](https://aws.amazon.com/lake-formation/)"]},
            {"week": "Week 8: Data Modeling & dbt", "goal": "Transforming data in the warehouse", "resources": ["[dbt Learn](https://courses.getdbt.com/)", "[Analytics Engineering Guide](https://www.getdbt.com/analytics-engineering/)", "[Jinja Templating](https://jinja.palletsprojects.com/)"]},
            {"week": "Week 9: Data Governance & Quality", "goal": "Great Expectations, data lineage", "resources": ["[Great Expectations](https://greatexpectations.io/)", "[Datahub Lineage](https://datahubproject.io/)", "[Data Quality Rules](https://www.collibra.com/)"]},
            {"week": "Week 10: Streaming ETL Pipeline Project", "goal": "Build an end-to-end Kafka-to-Snowflake pipeline", "resources": ["[Debezium CDC](https://debezium.io/)", "[Snowpipe Integration](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-intro)", "[Docker Compose Orchestration](https://docs.docker.com/compose/)"]}
        ]
    ],
    "full stack": [
        # Roadmap 1: MERN Stack
        [
            {"week": "Week 1: HTML/CSS & UI Fundamentals", "goal": "Flexbox, Grid, Responsive Design", "resources": ["[CSS Tricks Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)", "[MDN HTML](https://developer.mozilla.org/)", "[Frontend Mentor](https://www.frontendmentor.io/)"]},
            {"week": "Week 2: Advanced JavaScript", "goal": "Promises, Async/Await, ES6+", "resources": ["[JavaScript Info](https://javascript.info/)", "[You Don't Know JS](https://github.com/getify/You-Dont-Know-JS)", "[MDN Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)"]},
            {"week": "Week 3: React.js Foundations", "goal": "Components, Props, Hooks", "resources": ["[React Beta Docs](https://react.dev/)", "[Kent C Dodds Blog](https://kentcdodds.com/)", "[Scrimba React Crash Course](https://scrimba.com/)"]},
            {"week": "Week 4: Advanced React & State", "goal": "Redux, Context API, React Router", "resources": ["[Redux Toolkit](https://redux-toolkit.js.org/)", "[React Router Tutorial](https://reactrouter.com/)", "[Zustand](https://github.com/pmndrs/zustand)"]},
            {"week": "Week 5: Node.js & Express API", "goal": "RESTful Routing and Middleware", "resources": ["[Express Generator](https://expressjs.com/)", "[Node.js Architecture](https://nodejs.org/en/docs/guides/)", "[Postman Testing](https://www.postman.com/)"]},
            {"week": "Week 6: MongoDB Integration", "goal": "Mongoose Models, CRUD Operations", "resources": ["[Mongoose Docs](https://mongoosejs.com/)", "[MongoDB Atlas Setup](https://www.mongodb.com/cloud/atlas)", "[Aggregation Pipeline](https://www.mongodb.com/docs/manual/core/aggregation-pipeline/)"]},
            {"week": "Week 7: Authentication & Authorization", "goal": "Passport.js, JWT, BCrypt", "resources": ["[Passport.js Guide](https://www.passportjs.org/)", "[JWT Debugger](https://jwt.io/)", "[Web Security Basics](https://owasp.org/)"]},
            {"week": "Week 8: Application Styling", "goal": "TailwindCSS, Styled Components", "resources": ["[Tailwind Documentation](https://tailwindcss.com/)", "[Styled Components](https://styled-components.com/)", "[Framer Motion Animations](https://www.framer.com/motion/)"]},
            {"week": "Week 9: Testing & Debugging", "goal": "Jest, React Testing Library, Supertest", "resources": ["[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)", "[Jest Framework](https://jestjs.io/)", "[Cypress E2E](https://www.cypress.io/)"]},
            {"week": "Week 10: Production Deployment", "goal": "Deploy app on Vercel/Render", "resources": ["[Vercel Deployment](https://vercel.com/)", "[Render Web Services](https://render.com/)", "[GitHub Actions for CI/CD](https://docs.github.com/en/actions)"]}
        ],
        # Roadmap 2: Next.js + SQL Stack
        [
            {"week": "Week 1: TypeScript Crash Course", "goal": "Interfaces, Generics, types mapping", "resources": ["[TypeScript Handbook](https://www.typescriptlang.org/docs/)", "[TS for React](https://react-typescript-cheatsheet.netlify.app/)", "[Total TypeScript](https://www.totaltypescript.com/)"]},
            {"week": "Week 2: Next.js App Router Core", "goal": "RSCs, Layouts, Server Actions", "resources": ["[Next.js Documentation](https://nextjs.org/docs)", "[Vercel YouTube Tutorials](https://www.youtube.com/@Vercel)", "[Lee Robinson Blog](https://leerob.io/)"]},
            {"week": "Week 3: Advanced Next.js", "goal": "Caching, Middleware, API Routes", "resources": ["[Next.js Caching Strategies](https://nextjs.org/docs/app/building-your-application/caching)", "[Edge computing basics](https://vercel.com/features/edge-functions)", "[SWR/React Query](https://tanstack.com/query/latest)"]},
            {"week": "Week 4: Postgres & ORMs", "goal": "Prisma/Drizzle ORM setup", "resources": ["[Prisma Quickstart](https://www.prisma.io/docs/getting-started)", "[Drizzle ORM Docs](https://orm.drizzle.team/)", "[Supabase Database](https://supabase.com/)"]},
            {"week": "Week 5: Serverless Databases", "goal": "Neon, PlanetScale integrations", "resources": ["[Neon Postgres Platform](https://neon.tech/)", "[PlanetScale Tutorials](https://planetscale.com/)", "[SQL Connection Pooling](https://en.wikipedia.org/wiki/Connection_pool)"]},
            {"week": "Week 6: Modern UI Libraries", "goal": "Shadcn UI, Radix", "resources": ["[Shadcn UI Setup](https://ui.shadcn.com/)", "[Radix Primitives](https://www.radix-ui.com/)", "[Lucide Icons](https://lucide.dev/)"]},
            {"week": "Week 7: NextAuth Integration", "goal": "OAuth Providers, Session Management", "resources": ["[Auth.js (NextAuth)](https://authjs.dev/)", "[GitHub OAuth Setup](https://docs.github.com/)", "[Google Cloud Console (OAuth)](https://console.cloud.google.com/)"]},
            {"week": "Week 8: Form Handling & Validation", "goal": "React Hook Form, Zod constraints", "resources": ["[React Hook Form](https://react-hook-form.com/)", "[Zod Schema Validation](https://zod.dev/)", "[Server Action Validation](https://nextjs.org/docs)"]},
            {"week": "Week 9: Media Handling & Stripe", "goal": "S3 Uploads, Payment integrations", "resources": ["[UploadThing Tutorial](https://uploadthing.com/)", "[Stripe Developer Docs](https://stripe.com/docs)", "[Webhooks Guide](https://stripe.com/docs/webhooks)"]},
            {"week": "Week 10: Capstone SaaS Development", "goal": "Build a multi-tenant application", "resources": ["[Turborepo Monorepo](https://turbo.build/)", "[Stripe Subscriptions](https://stripe.com/billing)", "[Vercel Domains](https://vercel.com/docs/projects/domains)"]}
        ]
    ],
    "ui": [
        # Roadmap 1: UI/UX Designer
        [
            {"week": "Week 1: UX Foundations", "goal": "Design Thinking, User Personas", "resources": ["[Nielsen Norman Group](https://www.nngroup.com/)", "[Interaction Design Foundation](https://www.interaction-design.org/)", "[Laws of UX](https://lawsofux.com/)"]},
            {"week": "Week 2: Figma Mastery", "goal": "Frames, Auto-layout, Components", "resources": ["[Figma YouTube Channel](https://www.youtube.com/@Figma)", "[Figma Best Practices](https://help.figma.com/)", "[Design Systems Hub](https://www.designsystems.com/)"]},
            {"week": "Week 3: Wireframing & Prototyping", "goal": "Low vs High Fidelity", "resources": ["[Balsamiq Wireframing Academy](https://balsamiq.com/learn/)", "[Webflow Prototyping](https://webflow.com/)", "[InVision Inspiration](https://www.invisionapp.com/)"]},
            {"week": "Week 4: Color Theory & Typography", "goal": "Visual hierarchy, Accessibility", "resources": ["[ColorBrewer](https://colorbrewer2.org/)", "[Google Fonts Typography](https://fonts.google.com/knowledge)", "[WCAG Guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/)"]},
            {"week": "Week 5: Micro-interactions", "goal": "Animations, feedback loops", "resources": ["[LottieFiles](https://lottiefiles.com/)", "[Framer Templates](https://www.framer.com/)", "[UI Animation Principles](https://medium.com/ux-in-motion/creating-usability-with-motion-the-ux-in-motion-manifesto-a87a4584ddc)"]},
            {"week": "Week 6: User Research Methods", "goal": "A/B Testing, Heatmaps", "resources": ["[Hotjar Heatmaps](https://www.hotjar.com/)", "[Optimizely A/B Guide](https://www.optimizely.com/)", "[SurveyMonkey Templates](https://www.surveymonkey.com/)"]},
            {"week": "Week 7: Hand-off to Developers", "goal": "Zeplin, CSS generation", "resources": ["[Zeplin Learn](https://zeplin.io/)", "[Figma Dev Mode](https://www.figma.com/dev-mode/)", "[Storybook Intro](https://storybook.js.org/)"]},
            {"week": "Week 8: Designing for Mobile App", "goal": "iOS HIG and Material Design", "resources": ["[Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/)", "[Google Material 3](https://m3.material.io/)", "[Mobbin Mobile UI](https://mobbin.com/)"]},
            {"week": "Week 9: Constructing a Design System", "goal": "Design Tokens, Component Library", "resources": ["[Design Systems Repo](https://designsystemsrepo.com/)", "[Brad Frost Atomic Design](https://atomicdesign.bradfrost.com/)", "[Tokens Studio for Figma](https://tokens.studio/)"]},
            {"week": "Week 10: Portfolio Creation", "goal": "Publishing Case Studies", "resources": ["[Behance Examples](https://www.behance.net/)", "[Dribbble Portfolios](https://dribbble.com/)", "[Notion Portfolio Templates](https://www.notion.so/)"]}
        ],
        # Roadmap 2: Frontend UI Developer
        [
            {"week": "Week 1: Advanced CSS", "goal": "Animations, Grid, Preprocessors", "resources": ["[Sass Guidelines](https://sass-guidelin.es/)", "[CSS Grid Garden](https://cssgridgarden.com/)", "[Keyframe Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes)"]},
            {"week": "Week 2: Web Accessibility (a11y)", "goal": "ARIA roles, screen readers", "resources": ["[A11y Project](https://www.a11yproject.com/)", "[WAVE Evaluation Tool](https://wave.webaim.org/)", "[Axe Core Testing](https://github.com/dequelabs/axe-core)"]},
            {"week": "Week 3: CSS Frameworks", "goal": "TailwindCSS deep dive", "resources": ["[Tailwind Components](https://tailwindcomponents.com/)", "[Headless UI](https://headlessui.com/)", "[Tailwind UI Patterns](https://tailwindui.com/)"]},
            {"week": "Week 4: Frontend Framework React", "goal": "Translating UI designs to React", "resources": ["[React Component Patterns](https://www.patterns.dev/react)", "[Figma to HTML](https://www.figma.com/community/plugin)", "[CodeSandbox](https://codesandbox.io/)"]},
            {"week": "Week 5: State Management in UI", "goal": "Handling local and global visual states", "resources": ["[Zustand Docs](https://github.com/pmndrs/zustand)", "[React Context Guide](https://react.dev/reference/react/useContext)", "[Redux UI Patterns](https://redux.js.org/faq/design-decisions)"]},
            {"week": "Week 6: Complex Animations", "goal": "Framer Motion, GSAP", "resources": ["[GSAP Documentation](https://greensock.com/docs/)", "[Framer Motion Tutorials](https://www.youtube.com/)", "[Three.js Basics](https://threejs.org/)"]},
            {"week": "Week 7: Building Component Libraries", "goal": "Storybook integration", "resources": ["[Storybook Tutorials](https://storybook.js.org/tutorials/)", "[Bit Component Hub](https://bit.dev/)", "[NPM Publishing Guide](https://docs.npmjs.com/)"]},
            {"week": "Week 8: Performance Optimization", "goal": "Lighthouse scores, Core Web Vitals", "resources": ["[Web.Dev Vitals](https://web.dev/vitals/)", "[Chrome DevTools Panel](https://developer.chrome.com/docs/devtools/)", "[Image Optimization](https://imagekit.io/)"]},
            {"week": "Week 9: Cross-Browser Compatibility", "goal": "Testing across Safari/Chrome/Firefox", "resources": ["[BrowserStack Integration](https://www.browserstack.com/)", "[Caniuse Database](https://caniuse.com/)", "[Polyfills Guide](https://developer.mozilla.org/)"]},
            {"week": "Week 10: Real-Time UI Interactions", "goal": "WebSockets in Front-End", "resources": ["[Socket.io Client Docs](https://socket.io/)", "[WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)", "[Pusher Channels](https://pusher.com/)"]}
        ]
    ],
    "engineer": [
        # Roadmap 1: Broad Engineering Core
        [
            {"week": "Week 1: Fundamentals of Engineering", "goal": "Problem solving and logical thinking", "resources": ["[Brilliant.org Logic](https://brilliant.org/)", "[Polya's Problem Solving](https://math.berkeley.edu/~gbergman/ug.vcal/m74/PS/Polya.pdf)", "[Computational Thinking](https://www.bbc.co.uk/bitesize/guides/zp92mp3/revision/1)"]},
            {"week": "Week 2: Version Control & Tools", "goal": "Mastering Git, CLI, and IDEs", "resources": ["[Missing Semester of CS](https://missing.csail.mit.edu/)", "[Git Book](https://git-scm.com/book/en/v2)", "[VS Code Productivity](https://code.visualstudio.com/docs)"]},
            {"week": "Week 3: Algorithm Core", "goal": "Big-O, Searching, Sorting", "resources": ["[Khan Academy Computer Science](https://www.khanacademy.org/computing/computer-science)", "[VisuAlgo](https://visualgo.net/)", "[LeetCode Study Plan](https://leetcode.com/study-plan/)"]},
            {"week": "Week 4: Systems & Hardware Basics", "goal": "How computers actually work", "resources": ["[Crash Course CS](https://www.youtube.com/playlist?list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo)", "[Nand2Tetris](https://www.nand2tetris.org/)", "[Computer Architecture (CMU)](https://archive.org/)"]},
            {"week": "Week 5: Software Development Life Cycle (SDLC)", "goal": "Agile, DevOps, and CI/CD concepts", "resources": ["[Atlassian Agile Coach](https://www.atlassian.com/agile)", "[DevOps Roadmap](https://roadmap.sh/devops)", "[GitLab CI/CD Guide](https://docs.gitlab.com/ee/ci/)"]},
            {"week": "Week 6: High-Level Programming languages", "goal": "Python, Java, or C# paradigms", "resources": ["[Python Official Docs](https://docs.python.org/3/)", "[Java Oracle Tutorials](https://docs.oracle.com/javase/tutorial/)", "[Microsoft C# Guide](https://learn.microsoft.com/en-us/dotnet/csharp/)"]},
            {"week": "Week 7: Data Management", "goal": "File I/O, SQL, JSON structure", "resources": ["[SQL Zoo](https://sqlzoo.net/)", "[JSON Documentation](https://www.json.org/)", "[SQLite Tutorial](https://www.sqlitetutorial.net/)"]},
            {"week": "Week 8: Network Engineering Basics", "goal": "HTTP, TCP/IP, DNS", "resources": ["[How DNS Works](https://howdns.works/)", "[Mozilla HTTP Intro](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview)", "[Cisco Networking Intro](https://www.cisco.com/)"]},
            {"week": "Week 9: Security Foundations", "goal": "Cryptography, OWASP, Authentication", "resources": ["[OWASP Top 10](https://owasp.org/www-project-top-ten/)", "[Cryptography Crash Course](https://www.crypto101.io/)", "[Auth0 Concepts](https://auth0.com/)"]},
            {"week": "Week 10: System Design Capstone", "goal": "Designing scalable architectures on paper", "resources": ["[System Design Primer](https://github.com/donnemartin/system-design-primer)", "[InfoQ Architecture](https://www.infoq.com/architecture-design/)", "[AWS Architecture Center](https://aws.amazon.com/architecture/)"]}
        ],
        # Roadmap 2: Technical/DevOps Engineering
        [
            {"week": "Week 1: Linux Administration", "goal": "Bash, Permissions, Processes", "resources": ["[Linux Handbook](https://linuxhandbook.com/)", "[Bash Scripting Tutorial](https://linuxconfig.org/bash-scripting-tutorial)", "[OverTheWire Wargames](https://overthewire.org/wargames/bandit/)"]},
            {"week": "Week 2: Cloud Computing Core", "goal": "IAM, Compute, Storage in AWS/GCP", "resources": ["[AWS Training](https://aws.amazon.com/training/)", "[Google Cloud Skills Boost](https://www.cloudskillsboost.google/)", "[Microsoft Learn Azure](https://learn.microsoft.com/en-us/training/azure/)"]},
            {"week": "Week 3: Containerization Basics", "goal": "Docker images and volumes", "resources": ["[Docker Official Tutorials](https://docs.docker.com/get-started/)", "[Play with Docker](https://labs.play-with-docker.com/)", "[Docker Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)"]},
            {"week": "Week 4: Infrastructure as Code (IaC)", "goal": "Terraform, Ansible", "resources": ["[HashiCorp Learn Terraform](https://developer.hashicorp.com/terraform/tutorials)", "[Ansible Documentation](https://docs.ansible.com/)", "[Pulumi Docs](https://www.pulumi.com/docs/)"]},
            {"week": "Week 5: CI/CD Pipelines", "goal": "GitHub Actions, Jenkins", "resources": ["[Jenkins Pipeline Guide](https://www.jenkins.io/doc/book/pipeline/)", "[GitHub Actions Workflow](https://docs.github.com/en/actions)", "[CircleCI Docs](https://circleci.com/docs/)"]},
            {"week": "Week 6: Container Orchestration", "goal": "Kubernetes Architecture", "resources": ["[Kubernetes The Hard Way](https://github.com/kelseyhightower/kubernetes-the-hard-way)", "[Minikube Setup](https://minikube.sigs.k8s.io/docs/)", "[Rancher Academy](https://ranchermanager.docs.rancher.com/)"]},
            {"week": "Week 7: Observability & Logging", "goal": "Prometheus, Grafana, ELK Stack", "resources": ["[Prometheus Docs](https://prometheus.io/docs/introduction/overview/)", "[Grafana Tutorials](https://grafana.com/tutorials/)", "[Elastic Stack Intro](https://www.elastic.co/what-is/elk-stack)"]},
            {"week": "Week 8: Network Security & Firewalls", "goal": "VPCs, WAF, Zero Trust", "resources": ["[AWS WAF Guide](https://docs.aws.amazon.com/waf/)", "[Zero Trust Architecture](https://www.cloudflare.com/learning/security/glossary/what-is-zero-trust/)", "[Nginx Reverse Proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/)"]},
            {"week": "Week 9: Database Operations", "goal": "Backups, Replications, Migrations", "resources": ["[PostgreSQL High Availability](https://www.postgresql.org/docs/current/high-availability.html)", "[MongoDB Replication](https://www.mongodb.com/docs/manual/replication/)", "[Flyway Database Migration](https://flywaydb.org/)"]},
            {"week": "Week 10: Site Reliability Engineering", "goal": "SLIs, SLOs, Incident Response", "resources": ["[Google SRE Book](https://sre.google/sre-book/table-of-contents/)", "[PagerDuty Incident Response](https://response.pagerduty.com/)", "[Chaos Engineering](https://principlesofchaos.org/)"]}
        ]
    ]
}
